baseURL = "https://hypermineresearch.netlify.com/"
languageCode = "en-us"
title = "Hypermine Labs"
theme = "hugo-theme-okayish-blog"
copyright = "© Hypermine 2020"

[params]
# These will be used for OpenGraph, Twitter Card and Schema.org
description = "Brewing technology!"
keywords = ["identity", "blockchain", "security", "hypermine", "cryptography"]
#images = ["/images/banner.png"]
# Enable/disable share links (Facebook, Twitter and LinkedIn)
shareLinksEnabled = true

[taxonomies]
author = "authors"
tag = "tags"
category = "categories"

# Add menu items to the navigation bar as below.
# N.B. Use identifiers as the keys for translations.
[menu]

[[menu.main]]
identifier = "authors"
name = "Authors"
url = "/authors"

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories"

